### ISSUE TITLE
add chef-zero support

### ISSUE THREAD

**Issue by spigell** [melezhik/sparrowdo-chef-client#1]
Здравствуйте. Было бы неплохо добавить параметр, которым можно было бы указывать  на добавления ключа -z к chef-client и перехода в каталог с репозиторием. Можно ли это сделать?

**Comment by melezhik** [comment]
Приветствую! 
Думаю, что сделать будет не сложно.

**Comment by melezhik** [comment]
Здравствуйте! Попробуйте, пример тут - https://github.com/melezhik/sparrowdo-chef-client/blob/master/sparrowfile

**Comment by spigell** [comment]
Работает. Спасибо!
